### ISSUE TITLE
Introduction to Docker

### ISSUE THREAD

**Issue by mfrw** [ILUGD/talks#57] opened 2017-10-01 12:59 UTC
**Abstract**
	An light-hearted introduction to docker. The Talk is divided into 3 main parts. Part I will build a base for docker. Part II will dive into docker. Part III will touch on some advanced topics.
        
**Expected Duration**
    90 Mins

**Track**
        - Intermediate

**Pre-requisite**
   	Laptops
        
**Resources**
    https://docs.docker.com

**Slides**
    https://github.com/mfrw/talks/blob/master/docker-intro/docker-intro.pdf

**Comment by mysticTot** [comment] 2017-10-01 17:07
Thanks a lot for creating issue.

**Comment by mfrw** [comment] 2017-10-03 12:44
@aakash-garg-olx sure dude that is an awesome idea. The way I have structured my slides is that we first talk a little about the need for virtualization. Then a little about containers. Then we dive into docker. 
I agree talking about containers should be prior to this talk, but IMHO getting a hands on docker will get the audience ample experience to start using them effectively. 
If they want more information, they surely can read more.
[Just a point of view, fully open for discussion]

**Comment by aakash-garg-olx** [comment] 2017-10-04 06:02
@mfrw my approach to teaching Docker is to teach the audience about Linux Cgroups & Namespaces, and then Container Technology, then I would like to move to LXCs which was being used when there was no concept of Docker, after that, I would be doing hands-on on LXCs, and then I will move to Docker. 
Also, I would like to give some review on the slides created by you. I like the foundation part in the slides. But you are talking very less about the Containers and Docker examples which you are showcasing in the slides are not good examples. Examples must include the scenarios which are being used in the companies.

**Comment by mfrw** [comment] 2017-10-04 06:21
@aakash-garg-olx can you give me some pointers on what examples to include. I will update my slides accordingly :)

**Comment by aakash-garg-olx** [comment] 2017-10-04 06:53
@mfrw Try to setup Wordpress Site using Docker. Setup separate containers for the Wordpress site, MySQL, web server (Apache or Nginx). Connect all three together and set up the whole application. It is the good example to explain the working of the Docker. 
If you want to discuss more on this let me know.

**Comment by rajudev** [comment] 2017-10-10 20:57
No mentioned `chroots` here in the discussion. 

Also I would recommend that the workshops should be more hands-on than theoretical.
Only required enough concepts should be provided. 
Too much detail has resulted into over lengthy dragged talks in the past. I will hope that it won't be repeated in the same manner again. 
 People who are actually interested in the detail can read the documentations later.

**Comment by rajudev** [comment] 2017-10-11 05:07
@mfrw you already have an issue #14 with a similar title. Since this was created after that, this one is a duplicate of it. Right? Did you forgot that you already had an issue reported?

**Comment by mfrw** [comment] 2017-10-11 07:38
@rajudev Yes, I had forgotten about the earlier one. I thought that was closed. (my bad)
Sure I am planning to cut the slides so that we don't drag around much.

**Comment by mryashbhardwaj** [comment] 2017-10-11 08:42
@rajudev , @aakash-garg-olx , I am keen to attend this session. Since you guys are the experts in this domain, please suggest me some good theoretical/conceptual resources. So that I can come prepared and get the most from the event.

**Comment by rajudev** [comment] 2017-10-12 18:03
@mryashbhardwaj I am no expert. I know very little. I would suggest you trying creating a `chroot` understand what it is. then you try creating an `LXC container`, and then move towards `docker` . You will find sufficient resources on them over the web. Or you can ask on resources if needed in group or here.

**Comment by sourabhtk37** [comment] 2017-10-29 09:21
Thanks for the lovely talk. It was very insightful. @mfrw 
@aakash-garg-olx Would you like to propose a talk going a bit more deep?

**Comment by aakash-garg-olx** [comment] 2017-11-02 09:17
@sourabhtk37 I can try, but I would like to know, what things have been completed already. So that I think of the agenda to be delivered.

**Comment by sourabhtk37** [comment] 2017-11-02 14:33
>but I would like to know, what things have been completed already

@mfrw Pls to shed some light over this.

**Comment by mysticTot** [comment] 2017-11-02 14:38
@aakash-garg-olx , He covered basic  working of docker. You can refer slides for more details

**Comment by mfrw** [comment] 2017-11-02 16:54
@sourabhtk37 sure dude.
@aakash-garg-olx I covered the very very basics of containers. I tried to show a basic usage of docker, starting from `chroots`, then a little bit of `Jails & Zones`, some `LXC`, and then we straight away jumped to `Docker`.

I have two slides, which may give you a rough idea of what is covered. Although the second slide was not presented at ILUG-D, I covered the content verbally.

[docker-intro.pdf](https://github.com/ILUGD/talks/files/1438606/docker-intro.pdf)
[gdg_17.pdf](https://github.com/ILUGD/talks/files/1438607/gdg_17.pdf)

**Closed** 2017-11-20 15:38 UTC
Labels: delivered, finalised, proposal, workshop
